/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from '@tanstack/solid-router'

import type { AnyRoute } from '@tanstack/solid-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as DeckDeckIdRoute } from './routes/deck.$deckId'

const IndexRouteWithChildren = IndexRoute
const DeckDeckIdRouteWithChildren = DeckDeckIdRoute

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexRoute
    parentRoute: typeof rootRoute
  }
  '/deck/$deckId': {
    id: '/deck/$deckId'
    path: '/deck/$deckId'
    fullPath: '/deck/$deckId'
    preLoaderRoute: typeof DeckDeckIdRoute
    parentRoute: typeof rootRoute
  }
}

export const routeTree = rootRoute.addChildren({
  IndexRoute: IndexRouteWithChildren,
  DeckDeckIdRoute: DeckDeckIdRouteWithChildren,
})

/* prettier-ignore-end */
